### PR TITLE
Add support for MozMacosCrashInfoStream

### LINKED ISSUE #175: Support Mac Crash info
This was just added to mozilla's minidump-stackwalk: https://github.com/mozilla-services/minidump-stackwalk/pull/29

JSON Schema addition:

```json
    "mac_crash_info" : {
       "num_records" : 2,
       "records" : [
          {
             "message" : "CryptKit fatal error: Raise test exception from _pthread_cond_wait(2)",
             "module" : "/System/Library/Frameworks/Security.framework/Versions/A/Security"
          },
          {
             "message" : "abort() called",
             "module" : "/usr/lib/system/libsystem_c.dylib"
          }
       ]
    },
```

The information is in a new MOZ_MACOS_CRASH_INFO_STREAM section.

### PR DESCRIPTION
**Pull request by Gankra**
Fixes #175 

A bit of a mess because I had to copy the MISC_INFO multi_struct macros to fit this new format.

Also I did some drive-by cleanups on format.rs -- that one bitflags got shunted to the bottom of the file because it breaks syntax highlighting and that was making it harder to read my macro nightmares.

`MINIDUMP_LOCATION_DESCRIPTOR` got a `From<u8>` impl because that's what pread_derive uses for Array default.

### CODE REVIEW

**Comment by Gankra** [comment]
cc @steven-michaud

**Comment by luser** [comment]
Fascinating! TIL about this data. It looks like Crashpad captures this as well, but it translates it into their custom annotation stream format (which this crate recently gained support for, FWIW):
https://source.chromium.org/chromium/chromium/src/+/main:third_party/crashpad/crashpad/snapshot/module_snapshot.h;l=183;drc=778cf442a0040d196d9ce0aa870849c1fb698c83

**Comment by steven-michaud** [comment]
This looks fine to me, though I have a very limited understanding of Rust.

Let me know if you'd like some Firefox minidumps to test with (ones containing "mac crash info"). I can attach a few of my own here, if you'd like.

Hi, Ted! :-)

**Comment by Gankra** [comment]
Yeah I've already found a good test case. I think this is ready to land.

No tests for this one, it'd take me a lot of effort to wire up the synthetics for this one, and I'd rather not for something this niche.

**Pull request merged**
