### PR TITLE
Add fuzzer to minidump

### PR DESCRIPTION
**Pull request by 5225225**
All this does is tries to decode a minidump file and extract every known stream from it.

This is probably not going to see *all* the surface area (seeing as i'm not doing anything with the streams), but it should find *enough* for now. The fuzzer can always be improved in the future to cover more stuff.

This is finding multiple bugs, that I'll add fixes for in future PRs (One per bug, to make it easier both for me and easier to keep track of them).

Then once that's all done and the shallow bugs are done, might be worth getting this crate to be fuzzed as part of oss-fuzz.

### CODE REVIEW

**Comment by Gankra** [comment]
😮 

holy heck, this is, a shockingly simple PR. Thank you??

Gonna need to talk to a Fuzzing Person to understand what this does a bit better. (I am conceptually familiar with fuzzing but have never touched it, and am not aware of what the fuzzing landscape in Rust is.)

**Comment by 5225225** [comment]
Yeah, I like fuzzing because you get a *lot* of test coverage per line of test code. (I've contributed and ran... probably too many fuzzers over the last year (see: <https://github.com/rust-fuzz/trophy-case/pulls?q=is%3Apr+is%3Aclosed+author%3A5225225>), and half of them are literally just `let _ = crate_name::parse(input)`)

This uses https://github.com/rust-fuzz/cargo-fuzz with libfuzzer. Other Fuzzers Are Available (afl, hongfuzz), but I use libfuzzer because it's the default, and it's easy (and i'm lazy).

Though I've heard libfuzzer (or cargo-fuzz, not sure on which end the problem is) doesn't really work on windows.

Which isn't a problem for me, but I'd be happy to write an afl version (which, allegedly *does* work better on windows).

**Comment by Gankra** [comment]
Ah yeah, that does kinda suck for me since I work on windows by default (have a macbook in a pinch, but also just like my tooling to work well on Windows).

That said, these fuzzers aren't really something you would run with `cargo test` or anything right? I'm curious to what extent this stuff should be run in automation, or as part of some specific workflow.

Like presumably at least before cutting a release someone should run this? But for every PR..?

**Comment by Gankra** [comment]
Everywhere I'm checking seems to think Windows works fine now..? 

https://www.llvm.org/docs/LibFuzzer.html#q-does-libfuzzer-support-windows

**Comment by 5225225** [comment]
> That said, these fuzzers aren't really something you would run with cargo test or anything right?

Nah, fuzzers are more of an ongoing thing.

If you're Big and Professional you have machines that do nothing *but* fuzzing on whatever repos you own. (And if you're an Important library, which this crate very likely *does* qualify as, you can get google to continously fuzz you, see: https://google.github.io/oss-fuzz/ , which is an instance of google's ClusterFuzz which is basically a tool to manage a cluster of machines that fuzz stuff for you)

However, I've never used it, but apparently there's a CI friendly clusterfuzz that runs/can run for 10 minutes on every PR. See: https://google.github.io/clusterfuzzlite/running-clusterfuzzlite/

Might be worth looking into, although seems non-trivial to set up. Wouldn't be as good as something going long term, but it would catch shallow bugs that have been introduced that the existing tests don't find.

**Comment by 5225225** [comment]
> Everywhere I'm checking seems to think Windows works fine now..?

Ah, interesting. I don't have a windows machine to test on, so *maybe* it works now? I was just going off what I heard. Looking at the cargo-fuzz repo, they seem to say it works on WSL now (https://github.com/rust-fuzz/cargo-fuzz/issues/55), no mention about running it not in WSL.

**Comment by Gankra** [comment]
```
PS C:\Users\ninte\dev\rust-minidump\minidump> cargo fuzz run parse
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -Cpasses=sancov-module -Cllvm-args=-sanitizer-coverage-level=4 -Cllvm-args=-sanitizer-coverage-trace-compares -Cllvm-args=-sanitizer-coverage-inline-8bit-counters -Cllvm-args=-sanitizer-coverage-pc-table --cfg fuzzing -Clink-dead-code -Zsanitizer=address -Cdebug-assertions -C codegen-units=1 --target x86_64-pc-windows-msvc --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
  --- stdout
  ___.exe
  lib___.rlib
  ___.dll
  ___.dll
  ___.lib
  ___.dll
  C:\Users\ninte\.rustup\toolchains\nightly-x86_64-pc-windows-msvc
  debug_assertions
  fuzzing
  panic="unwind"
  proc_macro
  sanitize="address"
  target_abi=""
  target_arch="x86_64"
  target_endian="little"
  target_env="msvc"
  target_family="windows"
  target_feature="fxsr"
  target_feature="sse"
  target_feature="sse2"
  target_has_atomic="16"
  target_has_atomic="32"
  target_has_atomic="64"
  target_has_atomic="8"
  target_has_atomic="ptr"
  target_has_atomic_equal_alignment="16"
  target_has_atomic_equal_alignment="32"
  target_has_atomic_equal_alignment="64"
  target_has_atomic_equal_alignment="8"
  target_has_atomic_equal_alignment="ptr"
  target_has_atomic_load_store="16"
  target_has_atomic_load_store="32"
  target_has_atomic_load_store="64"
  target_has_atomic_load_store="8"
  target_has_atomic_load_store="ptr"
  target_os="windows"
  target_pointer_width="64"
  target_thread_local
  target_vendor="pc"
  windows

  --- stderr
  error: address sanitizer is not supported for this target

  error: aborting due to previous error

Error: failed to build fuzz script: "cargo" "build" "--manifest-path" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\Cargo.toml" "--target" "x86_64-pc-windows-msvc" "--release" "--bin" "parse"
PS C:\Users\ninte\dev\rust-minidump\minidump>
```

**Comment by 5225225** [comment]
Ah. Well, that explains that.

Though, since we barely use `unsafe` here, you don't really *need* sanitizers. Does it work if you run `cargo fuzz -s none run parse`, to run without any sanitizers?

**Comment by Gankra** [comment]
```
PS C:\Users\ninte\dev\rust-minidump\minidump> cargo fuzz run -s none parse
  Downloaded libfuzzer-sys v0.4.2
  Downloaded arbitrary v1.0.3
  Downloaded 2 crates (146.8 KB) in 0.49s
   Compiling autocfg v1.0.1
   Compiling proc-macro2 v1.0.36
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.86
   Compiling cc v1.0.72
   Compiling encoding_index_tests v0.1.4
   Compiling libc v0.2.114
   Compiling memchr v2.4.1
   Compiling winapi v0.3.9
   Compiling cfg-if v1.0.0
   Compiling log v0.4.14
   Compiling gimli v0.26.1
   Compiling failure_derive v0.1.8
   Compiling adler v1.0.2
   Compiling rustc-demangle v0.1.21
   Compiling bitflags v1.3.2
   Compiling arbitrary v1.0.3
   Compiling once_cell v1.9.0
   Compiling encoding-index-simpchinese v1.20141219.5
   Compiling encoding-index-japanese v1.20141219.5
   Compiling encoding-index-tradchinese v1.20141219.5
   Compiling encoding-index-singlebyte v1.20141219.5
   Compiling encoding-index-korean v1.20141219.5
   Compiling encoding v0.2.33
   Compiling num-traits v0.2.14
   Compiling miniz_oxide v0.4.4
   Compiling num-integer v0.1.44
   Compiling object v0.27.1
   Compiling quote v1.0.15
   Compiling backtrace v0.3.63
   Compiling libfuzzer-sys v0.4.2
   Compiling num-traits v0.1.43
   Compiling range-map v0.1.5
   Compiling time v0.1.44
   Compiling memmap v0.7.0
   Compiling chrono v0.4.19
   Compiling addr2line v0.17.0
   Compiling synstructure v0.12.6
   Compiling scroll_derive v0.10.5
   Compiling enum-primitive-derive v0.2.2
   Compiling smart-default v0.6.0
   Compiling failure v0.1.8
   Compiling scroll v0.10.2
   Compiling minidump-common v0.9.6 (C:\Users\ninte\dev\rust-minidump\minidump-common)
   Compiling minidump v0.9.6 (C:\Users\ninte\dev\rust-minidump\minidump)
   Compiling minidump-fuzz v0.0.0 (C:\Users\ninte\dev\rust-minidump\minidump\fuzz)
error: linking with `link.exe` failed: exit code: 1561
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\parse.parse.5c3a0e09-cgu.0.rcgu.o" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\parse.2xbowpk3egcemnct.rcgu.o" "/LIBPATH:C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps" "/LIBPATH:C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\release\\deps" "/LIBPATH:C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\build\\libfuzzer-sys-2e67110fd2bec5f4\\out" "/LIBPATH:C:\\Users\\ninte\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libminidump-bbe77c474ab3f15d.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libmemmap-54f08f102ad6ae52.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libfailure-71fb478d8c6255fe.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libbacktrace-54f051893f092a49.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\librustc_demangle-d0b1daeeedb6a96e.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libencoding-0d810bac1e429102.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libencoding_index_tradchinese-ddb8a5bf62b55fcf.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libencoding_index_simpchinese-bcca0f993188f6c7.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libencoding_index_japanese-44ad6e0d49ce1b6e.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libencoding_index_korean-5aa3586575dcfec0.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libencoding_index_singlebyte-097f5b32095535e0.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libchrono-e58bdcb14fcafb84.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libnum_integer-ca8fa8da1c4a33f3.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\liblibc-ed64461d9b1bde0a.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libtime-0ef272822dcb0451.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libwinapi-75b1426d35b5cd3e.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libminidump_common-18739b6ec0dba29b.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\librange_map-a3e0b88f4834f92d.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libnum_traits-7683a4ee4200aeba.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libbitflags-02cfb3cde8dff2f0.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libnum_traits-1239a8fa3d99cf23.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\liblog-010460c21afd75a8.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libcfg_if-e445ba07a17495da.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libscroll-a7b6c7b4bcfab29f.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\liblibfuzzer_sys-d0c826e362942740.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libonce_cell-266fd9ecd056b497.rlib" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\libarbitrary-db3b6eb35c11dd51.rlib" "C:\\Users\\ninte\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-8db3722c96fb491d.rlib" "C:\\Users\\ninte\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-ee8804a073a629b8.rlib" "C:\\Users\\ninte\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd_detect-f320e82b0baaad6d.rlib" "C:\\Users\\ninte\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-cede8d1fca99fc93.rlib" "C:\\Users\\ninte\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-77064ce859f56901.rlib" "C:\\Users\\ninte\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-31a385e2e15a7a71.rlib" "C:\\Users\\ninte\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-c431fe701788effd.rlib" "C:\\Users\\ninte\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-9c55022353a90ed5.rlib" "C:\\Users\\ninte\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-5c6e234e3431724c.rlib" "C:\\Users\\ninte\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-c4009c6b42e3b42a.rlib" "C:\\Users\\ninte\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-665ed95809278e59.rlib" "C:\\Users\\ninte\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-c2100e40c13f915d.rlib" "C:\\Users\\ninte\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-e57a7d82dcc1d66d.rlib" "advapi32.lib" "kernel32.lib" "kernel32.lib" "ws2_32.lib" "bcrypt.lib" "advapi32.lib" "userenv.lib" "kernel32.lib" "msvcrt.lib" "/NXCOMPAT" "/LIBPATH:C:\\Users\\ninte\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/OUT:C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\target\\x86_64-pc-windows-msvc\\release\\deps\\parse.exe" "/DEBUG" "/NATVIS:C:\\Users\\ninte\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\ninte\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\ninte\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\ninte\\.rustup\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis"
  = note:    Creating library C:\Users\ninte\dev\rust-minidump\minidump\fuzz\target\x86_64-pc-windows-msvc\release\deps\parse.lib and object C:\Users\ninte\dev\rust-minidump\minidump\fuzz\target\x86_64-pc-windows-msvc\release\deps\parse.exp
          LINK : fatal error LNK1561: entry point must be defined


error: could not compile `minidump-fuzz` due to previous error
Error: failed to build fuzz script: "cargo" "build" "--manifest-path" "C:\\Users\\ninte\\dev\\rust-minidump\\minidump\\fuzz\\Cargo.toml" "--target" "x86_64-pc-windows-msvc" "--release" "--bin" "parse"
```

**Comment by Gankra** [comment]
Seems like it *wants* to work...

**Comment by luser** [comment]
> All this does is tries to decode a minidump file and extract every known stream from it.
> 
> This is probably not going to see _all_ the surface area (seeing as i'm not doing anything with the streams), but it should find _enough_ for now. The fuzzer can always be improved in the future to cover more stuff.

Cool! In terms of fuzzing this is probably one of the two biggest pieces that are valuable. Most of the API surface on the minidump stream objects just hands out already-parsed bits of data.

The other two parts that would be most valuable would be:

1. Symbol file parsing, pretty much just [`SymbolFile::parse`](https://github.com/luser/rust-minidump/blob/1c5f5f81f4431f358d5342c7e1114b0737949474/breakpad-symbols/src/sym_file/mod.rs#L27)
2. Stack unwinding, since we're groveling for data from stack memory in the minidump and whatnot. This is a bit more of a PITA since it requires a whole pile of data in place to do anything useful. You can look at the test fixtures in [the x86 stackwalker tests](https://github.com/luser/rust-minidump/blob/1c5f5f81f4431f358d5342c7e1114b0737949474/minidump-processor/src/stackwalker/x86_unittest.rs) for an example of what I mean.

Given that the minidump files come from untrusted client machines, what you've got here is already fantastic and super valuable. Thank you!

**Comment by Gankra** [comment]
I'm going to accept this as-is so you don't need to worry about rebasing it. Even if running it on windows is hard, it's great stuff that's worth having in-tree. We can refine it more if we find time.

**Pull request merged**
