### PR TITLE
WIP rework minidump-common a bit

### PR DESCRIPTION
**Pull request by Gankra**
I'm thinking about what should be done for #126, which would introduce more crates that
care about minidump-common and make it more of a 'product'. Most importantly we need to
derive Pwrite so a minidump client can use those type definitions to write.

I pulled out the error types to separate modules to make it easier to maintain the core
format.rs file. It was getting a bit unwieldy. For now I pub use the error modules back
into format.rs to keep things working the same, but I think longterm they probably want
to be totally separate and maybe even possible to disable with a feature?

traits.rs also really has no business existing in this context. We could also hide it
being a feature or split minidump-common into two crates, format.rs and traits.rs.
Possibly the former would be justifiably called 'minidump-sys', although I think that's
technically an abuse of naming convention since we don't link with a native minidump lib.

### CODE REVIEW

**Comment by Gankra** [comment]
Oh whoops I accidentally committed my change to the example to test writing works right.

**Comment by Gankra** [comment]
cc @gabrielesvelto since errors are "your" component.

**Comment by Gankra** [comment]
NB I am hoping to use this for https://bugzilla.mozilla.org/show_bug.cgi?id=1620991, but maybe it's a better use of time to just copy whatever https://github.com/msirringhaus/minidump_writer_linux does?

**Comment by gabrielesvelto** [comment]
Breaking out the error/exception codes is a good idea, makes the core stuff more manageable. That's especially true considering that those files will change very, very rarely (like once every 1-2 years when Microsoft updates its public headers). This has another benefit for me (and possibly others too): probably due to a bug or limitation in the rust analyzer parsing format.rs would OOM it (on a machine with 32 GiB of memory). It started happening when I first introduced the list of Windows error, so having it in a separate place most certainly helps.

**Comment by luser** [comment]
More generally, `format.rs` being one gigantic file dates back to the time where I was using `bindgen` to convert the struct definitions from Breakpad's headers into Rust as a starting point. They're now hand-authored, so reorganizing them is very reasonable.

**Comment by Gankra** [comment]
(letting this bitrot until ~january to minimize major changes while we're deploying this to socorro)

**Comment by Gankra** [comment]
this has bitrotted to all hell

**Pull request closed without merging**
