### PR TITLE
Add breakpad_symbol SymbolFile fuzzer

### PR DESCRIPTION
**Pull request by 5225225**
Going to leave this running overnight. Could find something else, because it was previously exiting early because of the (now fixed in #419) overflow.

I looked in the rest of this crate, and couldn't really see anything doing much complex work.

### CODE REVIEW

**Comment by luser** [comment]
420, fuzz it. :sunglasses:

**Comment by 5225225** [comment]
:sunglasses: 

time to write that stack walk fuzzer you warned me about

**Review by Gankra — APPROVED** [review]

**Comment by Gankra** [comment]
rad!

**Comment by luser** [comment]
> time to write that stack walk fuzzer you warned me about

:sweat_smile: If you want to chat about potential approaches to this feel free to join us [in Sentry's discord](https://open.sentry.io/), the #native-crashes channel, or via [Twitter DM](https://mobile.twitter.com/TedMielczarek). I will say that while it's an interesting idea, in terms of bang-for-the-buck you've already covered the most useful fuzz targets at this point.

**Pull request merged**
