### PR TITLE
Properly read csd_version

### LINKED ISSUE #270: os_ver not being properly set on linux
https://crash-stats.mozilla.org/report/index/827f16ea-b880-4958-b5a1-d8d060211029

socorro:
```
"os_ver": "0.0.0 Linux 5.14.15-300.fc35.x86_64 #1 SMP Wed Oct 27 15:53:39 UTC 2021 x86_64"
```

rust-minidump:

```
"os_ver": "0.0.0"
```

### PR DESCRIPTION
**Pull request by Gankra**
Wrong array was being passed in.

Fixes #270

### CODE REVIEW

**Comment by Gankra** [comment]
...oh weird

this breaks the test minidump. not sure if that's messed up or if windows and linux use this rva inconsistently? hmm

**Comment by Gankra** [comment]
@luser if you have any insights on why windows and linux would be different (and why I don't obviously see how breakpad manages that), I'd love to know.

Personally baffled.

**Comment by Gankra** [comment]
OH

It wasn't failing because I *broke* the test.

It was failing because I *fixed* the broken test lol.

**Comment by luser** [comment]
Nice! Wow, what a silly bug!

**Comment by gabrielesvelto** [comment]
Proof that Rust can't prevent you from occasionally shooting yourself in the foot, but when you do at worst it's with a nerf gun.

**Pull request merged**
