### PR TITLE
add optional vendored-openssl feature

### PR DESCRIPTION
**Pull request by Gankra**
context: 

https://github.com/mozilla/dump_syms/blob/bf7f6bd855eb6ecb233b52bfa7b2c975b7026540/Cargo.toml#L40-L45

https://searchfox.org/mozilla-central/rev/6deb8b6af57a8b5b6b1bcb143ea498e566475d8d/taskcluster/scripts/misc/build-dump-syms.sh#52

### CODE REVIEW

**Comment by Gankra** [comment]
@gabrielesvelto do you know the historical context for why our linux builds for dump_syms do this? Currently just assuming it's necessary. The build on taskcluster *does* fail for rust-minidump if I don't do this:

```
[task 2021-11-16T23:09:47.421Z] The following warnings were emitted during compilation:
[task 2021-11-16T23:09:47.422Z] 
[task 2021-11-16T23:09:47.422Z] warning: build/expando.c:2:10: fatal error: 'openssl/opensslconf.h' file not found
[task 2021-11-16T23:09:47.422Z] warning: #include <openssl/opensslconf.h>
[task 2021-11-16T23:09:47.422Z] warning:          ^~~~~~~~~~~~~~~~~~~~~~~
[task 2021-11-16T23:09:47.422Z] warning: 1 error generated.
[task 2021-11-16T23:09:47.422Z] 
[task 2021-11-16T23:09:47.422Z] error: failed to run custom build command for `openssl-sys v0.9.63`
[task 2021-11-16T23:09:47.422Z] 
```

**Comment by gabrielesvelto** [comment]
> @gabrielesvelto do you know the historical context for why our linux builds for dump_syms do this?

It's an issue that predates dump_syms, I think it's best explained in [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1163171#c26) and the current version of things first happened with sccache IIRC (see [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1617143)).

**Comment by Gankra** [comment]
Ok so tl;dr the docker images we build inside of use a weird symbol/path for OpenSSL which would cause portability/build issues, and the simplest solution we found was to statically link it and not worry about it. Seems ~fine.

**Comment by luser** [comment]
I agree, if this gets you unstuck then it's fine. The only thing that should be using `openssl` in this crate is the symbol-fetching-via-HTTPS code in `breakpad-symbols`, and that's just transitively by way of `native-tls`.

**Pull request merged**
